// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserActionLog.proto

package com.yiban.serde.protobuf.model;

public interface UserActionLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yiban.serde.protobuf.model.UserActionLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string actionType = 2;</code>
   * @return The actionType.
   */
  java.lang.String getActionType();
  /**
   * <code>string actionType = 2;</code>
   * @return The bytes for actionType.
   */
  com.google.protobuf.ByteString
      getActionTypeBytes();

  /**
   * <code>string ipAddress = 3;</code>
   * @return The ipAddress.
   */
  java.lang.String getIpAddress();
  /**
   * <code>string ipAddress = 3;</code>
   * @return The bytes for ipAddress.
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <code>int32 gender = 4;</code>
   * @return The gender.
   */
  int getGender();

  /**
   * <code>string provience = 5;</code>
   * @return The provience.
   */
  java.lang.String getProvience();
  /**
   * <code>string provience = 5;</code>
   * @return The bytes for provience.
   */
  com.google.protobuf.ByteString
      getProvienceBytes();
}
