// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserActionLog.proto

package com.yiban.serde.protobuf.model;

public final class UserActionLogModel {
  private UserActionLogModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yiban_serde_protobuf_model_UserActionLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yiban_serde_protobuf_model_UserActionLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023UserActionLog.proto\022\036com.yiban.serde.p" +
      "rotobuf.model\"k\n\rUserActionLog\022\020\n\010userNa" +
      "me\030\001 \001(\t\022\022\n\nactionType\030\002 \001(\t\022\021\n\tipAddres" +
      "s\030\003 \001(\t\022\016\n\006gender\030\004 \001(\005\022\021\n\tprovience\030\005 \001" +
      "(\tB6\n\036com.yiban.serde.protobuf.modelB\022Us" +
      "erActionLogModelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_yiban_serde_protobuf_model_UserActionLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yiban_serde_protobuf_model_UserActionLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yiban_serde_protobuf_model_UserActionLog_descriptor,
        new java.lang.String[] { "UserName", "ActionType", "IpAddress", "Gender", "Provience", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
